language: ruby
rvm:
  - 2.6.5

cache:
  # - bundler

before_script: 
  - bundle install
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create

script:
  - bundle exec rake db:migrate:reset RAILS_ENV=test
  - bundle exec rspec